# Generated by Django 4.0.4 on 2022-05-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosemodel',
            name='upload',
            field=models.FileField(upload_to='media'),
        ),
    ]
